import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({
	weight: ['400', '500', '600', '700', '800'],
	subsets: ['latin'],
})
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

import React, { FC } from 'react'
import { ChildPops } from '@/types'

const RootLayout: FC<ChildPops> = ({ children }) => {
	return (
		<html lang='en'>
			<body className={`${montserrat.className} antialiased`}>
				<main className='container max-w-6xl mt-24'>{children}</main>
			</body>
		</html>
	)
}

export default RootLayout
